// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package info

import (
	"fmt"
	"strings"
)

const (
	// AttributesRequestFilterVisibilityALL is a AttributesRequestFilterVisibility of type ALL.
	AttributesRequestFilterVisibilityALL AttributesRequestFilterVisibility = iota
	// AttributesRequestFilterVisibilityVISIBLE is a AttributesRequestFilterVisibility of type VISIBLE.
	AttributesRequestFilterVisibilityVISIBLE
	// AttributesRequestFilterVisibilityINVISIBLE is a AttributesRequestFilterVisibility of type INVISIBLE.
	AttributesRequestFilterVisibilityINVISIBLE
	// AttributesRequestFilterVisibilityEMPTYSTOCK is a AttributesRequestFilterVisibility of type EMPTY_STOCK.
	AttributesRequestFilterVisibilityEMPTYSTOCK
	// AttributesRequestFilterVisibilityNOTMODERATED is a AttributesRequestFilterVisibility of type NOT_MODERATED.
	AttributesRequestFilterVisibilityNOTMODERATED
	// AttributesRequestFilterVisibilityMODERATED is a AttributesRequestFilterVisibility of type MODERATED.
	AttributesRequestFilterVisibilityMODERATED
	// AttributesRequestFilterVisibilityDISABLED is a AttributesRequestFilterVisibility of type DISABLED.
	AttributesRequestFilterVisibilityDISABLED
	// AttributesRequestFilterVisibilitySTATEFAILED is a AttributesRequestFilterVisibility of type STATE_FAILED.
	AttributesRequestFilterVisibilitySTATEFAILED
	// AttributesRequestFilterVisibilityREADYTOSUPPLY is a AttributesRequestFilterVisibility of type READY_TO_SUPPLY.
	AttributesRequestFilterVisibilityREADYTOSUPPLY
	// AttributesRequestFilterVisibilityVALIDATIONSTATEPENDING is a AttributesRequestFilterVisibility of type VALIDATION_STATE_PENDING.
	AttributesRequestFilterVisibilityVALIDATIONSTATEPENDING
	// AttributesRequestFilterVisibilityVALIDATIONSTATEFAIL is a AttributesRequestFilterVisibility of type VALIDATION_STATE_FAIL.
	AttributesRequestFilterVisibilityVALIDATIONSTATEFAIL
	// AttributesRequestFilterVisibilityVALIDATIONSTATESUCCESS is a AttributesRequestFilterVisibility of type VALIDATION_STATE_SUCCESS.
	AttributesRequestFilterVisibilityVALIDATIONSTATESUCCESS
	// AttributesRequestFilterVisibilityTOSUPPLY is a AttributesRequestFilterVisibility of type TO_SUPPLY.
	AttributesRequestFilterVisibilityTOSUPPLY
	// AttributesRequestFilterVisibilityINSALE is a AttributesRequestFilterVisibility of type IN_SALE.
	AttributesRequestFilterVisibilityINSALE
	// AttributesRequestFilterVisibilityREMOVEDFROMSALE is a AttributesRequestFilterVisibility of type REMOVED_FROM_SALE.
	AttributesRequestFilterVisibilityREMOVEDFROMSALE
	// AttributesRequestFilterVisibilityBANNED is a AttributesRequestFilterVisibility of type BANNED.
	AttributesRequestFilterVisibilityBANNED
	// AttributesRequestFilterVisibilityOVERPRICED is a AttributesRequestFilterVisibility of type OVERPRICED.
	AttributesRequestFilterVisibilityOVERPRICED
	// AttributesRequestFilterVisibilityCRITICALLYOVERPRICED is a AttributesRequestFilterVisibility of type CRITICALLY_OVERPRICED.
	AttributesRequestFilterVisibilityCRITICALLYOVERPRICED
	// AttributesRequestFilterVisibilityEMPTYBARCODE is a AttributesRequestFilterVisibility of type EMPTY_BARCODE.
	AttributesRequestFilterVisibilityEMPTYBARCODE
	// AttributesRequestFilterVisibilityBARCODEEXISTS is a AttributesRequestFilterVisibility of type BARCODE_EXISTS.
	AttributesRequestFilterVisibilityBARCODEEXISTS
	// AttributesRequestFilterVisibilityQUARANTINE is a AttributesRequestFilterVisibility of type QUARANTINE.
	AttributesRequestFilterVisibilityQUARANTINE
	// AttributesRequestFilterVisibilityARCHIVED is a AttributesRequestFilterVisibility of type ARCHIVED.
	AttributesRequestFilterVisibilityARCHIVED
	// AttributesRequestFilterVisibilityOVERPRICEDWITHSTOCK is a AttributesRequestFilterVisibility of type OVERPRICED_WITH_STOCK.
	AttributesRequestFilterVisibilityOVERPRICEDWITHSTOCK
	// AttributesRequestFilterVisibilityPARTIALAPPROVED is a AttributesRequestFilterVisibility of type PARTIAL_APPROVED.
	AttributesRequestFilterVisibilityPARTIALAPPROVED
	// AttributesRequestFilterVisibilityIMAGEABSENT is a AttributesRequestFilterVisibility of type IMAGE_ABSENT.
	AttributesRequestFilterVisibilityIMAGEABSENT
	// AttributesRequestFilterVisibilityMODERATIONBLOCK is a AttributesRequestFilterVisibility of type MODERATION_BLOCK.
	AttributesRequestFilterVisibilityMODERATIONBLOCK
)

var ErrInvalidAttributesRequestFilterVisibility = fmt.Errorf("not a valid AttributesRequestFilterVisibility, try [%s]", strings.Join(_AttributesRequestFilterVisibilityNames, ", "))

const _AttributesRequestFilterVisibilityName = "ALLVISIBLEINVISIBLEEMPTY_STOCKNOT_MODERATEDMODERATEDDISABLEDSTATE_FAILEDREADY_TO_SUPPLYVALIDATION_STATE_PENDINGVALIDATION_STATE_FAILVALIDATION_STATE_SUCCESSTO_SUPPLYIN_SALEREMOVED_FROM_SALEBANNEDOVERPRICEDCRITICALLY_OVERPRICEDEMPTY_BARCODEBARCODE_EXISTSQUARANTINEARCHIVEDOVERPRICED_WITH_STOCKPARTIAL_APPROVEDIMAGE_ABSENTMODERATION_BLOCK"

var _AttributesRequestFilterVisibilityNames = []string{
	_AttributesRequestFilterVisibilityName[0:3],
	_AttributesRequestFilterVisibilityName[3:10],
	_AttributesRequestFilterVisibilityName[10:19],
	_AttributesRequestFilterVisibilityName[19:30],
	_AttributesRequestFilterVisibilityName[30:43],
	_AttributesRequestFilterVisibilityName[43:52],
	_AttributesRequestFilterVisibilityName[52:60],
	_AttributesRequestFilterVisibilityName[60:72],
	_AttributesRequestFilterVisibilityName[72:87],
	_AttributesRequestFilterVisibilityName[87:111],
	_AttributesRequestFilterVisibilityName[111:132],
	_AttributesRequestFilterVisibilityName[132:156],
	_AttributesRequestFilterVisibilityName[156:165],
	_AttributesRequestFilterVisibilityName[165:172],
	_AttributesRequestFilterVisibilityName[172:189],
	_AttributesRequestFilterVisibilityName[189:195],
	_AttributesRequestFilterVisibilityName[195:205],
	_AttributesRequestFilterVisibilityName[205:226],
	_AttributesRequestFilterVisibilityName[226:239],
	_AttributesRequestFilterVisibilityName[239:253],
	_AttributesRequestFilterVisibilityName[253:263],
	_AttributesRequestFilterVisibilityName[263:271],
	_AttributesRequestFilterVisibilityName[271:292],
	_AttributesRequestFilterVisibilityName[292:308],
	_AttributesRequestFilterVisibilityName[308:320],
	_AttributesRequestFilterVisibilityName[320:336],
}

// AttributesRequestFilterVisibilityNames returns a list of possible string values of AttributesRequestFilterVisibility.
func AttributesRequestFilterVisibilityNames() []string {
	tmp := make([]string, len(_AttributesRequestFilterVisibilityNames))
	copy(tmp, _AttributesRequestFilterVisibilityNames)
	return tmp
}

var _AttributesRequestFilterVisibilityMap = map[AttributesRequestFilterVisibility]string{
	AttributesRequestFilterVisibilityALL:                    _AttributesRequestFilterVisibilityName[0:3],
	AttributesRequestFilterVisibilityVISIBLE:                _AttributesRequestFilterVisibilityName[3:10],
	AttributesRequestFilterVisibilityINVISIBLE:              _AttributesRequestFilterVisibilityName[10:19],
	AttributesRequestFilterVisibilityEMPTYSTOCK:             _AttributesRequestFilterVisibilityName[19:30],
	AttributesRequestFilterVisibilityNOTMODERATED:           _AttributesRequestFilterVisibilityName[30:43],
	AttributesRequestFilterVisibilityMODERATED:              _AttributesRequestFilterVisibilityName[43:52],
	AttributesRequestFilterVisibilityDISABLED:               _AttributesRequestFilterVisibilityName[52:60],
	AttributesRequestFilterVisibilitySTATEFAILED:            _AttributesRequestFilterVisibilityName[60:72],
	AttributesRequestFilterVisibilityREADYTOSUPPLY:          _AttributesRequestFilterVisibilityName[72:87],
	AttributesRequestFilterVisibilityVALIDATIONSTATEPENDING: _AttributesRequestFilterVisibilityName[87:111],
	AttributesRequestFilterVisibilityVALIDATIONSTATEFAIL:    _AttributesRequestFilterVisibilityName[111:132],
	AttributesRequestFilterVisibilityVALIDATIONSTATESUCCESS: _AttributesRequestFilterVisibilityName[132:156],
	AttributesRequestFilterVisibilityTOSUPPLY:               _AttributesRequestFilterVisibilityName[156:165],
	AttributesRequestFilterVisibilityINSALE:                 _AttributesRequestFilterVisibilityName[165:172],
	AttributesRequestFilterVisibilityREMOVEDFROMSALE:        _AttributesRequestFilterVisibilityName[172:189],
	AttributesRequestFilterVisibilityBANNED:                 _AttributesRequestFilterVisibilityName[189:195],
	AttributesRequestFilterVisibilityOVERPRICED:             _AttributesRequestFilterVisibilityName[195:205],
	AttributesRequestFilterVisibilityCRITICALLYOVERPRICED:   _AttributesRequestFilterVisibilityName[205:226],
	AttributesRequestFilterVisibilityEMPTYBARCODE:           _AttributesRequestFilterVisibilityName[226:239],
	AttributesRequestFilterVisibilityBARCODEEXISTS:          _AttributesRequestFilterVisibilityName[239:253],
	AttributesRequestFilterVisibilityQUARANTINE:             _AttributesRequestFilterVisibilityName[253:263],
	AttributesRequestFilterVisibilityARCHIVED:               _AttributesRequestFilterVisibilityName[263:271],
	AttributesRequestFilterVisibilityOVERPRICEDWITHSTOCK:    _AttributesRequestFilterVisibilityName[271:292],
	AttributesRequestFilterVisibilityPARTIALAPPROVED:        _AttributesRequestFilterVisibilityName[292:308],
	AttributesRequestFilterVisibilityIMAGEABSENT:            _AttributesRequestFilterVisibilityName[308:320],
	AttributesRequestFilterVisibilityMODERATIONBLOCK:        _AttributesRequestFilterVisibilityName[320:336],
}

// String implements the Stringer interface.
func (x AttributesRequestFilterVisibility) String() string {
	if str, ok := _AttributesRequestFilterVisibilityMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AttributesRequestFilterVisibility(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AttributesRequestFilterVisibility) IsValid() bool {
	_, ok := _AttributesRequestFilterVisibilityMap[x]
	return ok
}

var _AttributesRequestFilterVisibilityValue = map[string]AttributesRequestFilterVisibility{
	_AttributesRequestFilterVisibilityName[0:3]:     AttributesRequestFilterVisibilityALL,
	_AttributesRequestFilterVisibilityName[3:10]:    AttributesRequestFilterVisibilityVISIBLE,
	_AttributesRequestFilterVisibilityName[10:19]:   AttributesRequestFilterVisibilityINVISIBLE,
	_AttributesRequestFilterVisibilityName[19:30]:   AttributesRequestFilterVisibilityEMPTYSTOCK,
	_AttributesRequestFilterVisibilityName[30:43]:   AttributesRequestFilterVisibilityNOTMODERATED,
	_AttributesRequestFilterVisibilityName[43:52]:   AttributesRequestFilterVisibilityMODERATED,
	_AttributesRequestFilterVisibilityName[52:60]:   AttributesRequestFilterVisibilityDISABLED,
	_AttributesRequestFilterVisibilityName[60:72]:   AttributesRequestFilterVisibilitySTATEFAILED,
	_AttributesRequestFilterVisibilityName[72:87]:   AttributesRequestFilterVisibilityREADYTOSUPPLY,
	_AttributesRequestFilterVisibilityName[87:111]:  AttributesRequestFilterVisibilityVALIDATIONSTATEPENDING,
	_AttributesRequestFilterVisibilityName[111:132]: AttributesRequestFilterVisibilityVALIDATIONSTATEFAIL,
	_AttributesRequestFilterVisibilityName[132:156]: AttributesRequestFilterVisibilityVALIDATIONSTATESUCCESS,
	_AttributesRequestFilterVisibilityName[156:165]: AttributesRequestFilterVisibilityTOSUPPLY,
	_AttributesRequestFilterVisibilityName[165:172]: AttributesRequestFilterVisibilityINSALE,
	_AttributesRequestFilterVisibilityName[172:189]: AttributesRequestFilterVisibilityREMOVEDFROMSALE,
	_AttributesRequestFilterVisibilityName[189:195]: AttributesRequestFilterVisibilityBANNED,
	_AttributesRequestFilterVisibilityName[195:205]: AttributesRequestFilterVisibilityOVERPRICED,
	_AttributesRequestFilterVisibilityName[205:226]: AttributesRequestFilterVisibilityCRITICALLYOVERPRICED,
	_AttributesRequestFilterVisibilityName[226:239]: AttributesRequestFilterVisibilityEMPTYBARCODE,
	_AttributesRequestFilterVisibilityName[239:253]: AttributesRequestFilterVisibilityBARCODEEXISTS,
	_AttributesRequestFilterVisibilityName[253:263]: AttributesRequestFilterVisibilityQUARANTINE,
	_AttributesRequestFilterVisibilityName[263:271]: AttributesRequestFilterVisibilityARCHIVED,
	_AttributesRequestFilterVisibilityName[271:292]: AttributesRequestFilterVisibilityOVERPRICEDWITHSTOCK,
	_AttributesRequestFilterVisibilityName[292:308]: AttributesRequestFilterVisibilityPARTIALAPPROVED,
	_AttributesRequestFilterVisibilityName[308:320]: AttributesRequestFilterVisibilityIMAGEABSENT,
	_AttributesRequestFilterVisibilityName[320:336]: AttributesRequestFilterVisibilityMODERATIONBLOCK,
}

// ParseAttributesRequestFilterVisibility attempts to convert a string to a AttributesRequestFilterVisibility.
func ParseAttributesRequestFilterVisibility(name string) (AttributesRequestFilterVisibility, error) {
	if x, ok := _AttributesRequestFilterVisibilityValue[name]; ok {
		return x, nil
	}
	return AttributesRequestFilterVisibility(0), fmt.Errorf("%s is %w", name, ErrInvalidAttributesRequestFilterVisibility)
}

// MarshalText implements the text marshaller method.
func (x AttributesRequestFilterVisibility) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AttributesRequestFilterVisibility) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseAttributesRequestFilterVisibility(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

const (
	// AttributesResponseResultDimensionUnitMm is a AttributesResponseResultDimensionUnit of type Mm.
	AttributesResponseResultDimensionUnitMm AttributesResponseResultDimensionUnit = iota + 1
	// AttributesResponseResultDimensionUnitCm is a AttributesResponseResultDimensionUnit of type Cm.
	AttributesResponseResultDimensionUnitCm
	// AttributesResponseResultDimensionUnitIn is a AttributesResponseResultDimensionUnit of type In.
	AttributesResponseResultDimensionUnitIn
)

var ErrInvalidAttributesResponseResultDimensionUnit = fmt.Errorf("not a valid AttributesResponseResultDimensionUnit, try [%s]", strings.Join(_AttributesResponseResultDimensionUnitNames, ", "))

const _AttributesResponseResultDimensionUnitName = "mmcmin"

var _AttributesResponseResultDimensionUnitNames = []string{
	_AttributesResponseResultDimensionUnitName[0:2],
	_AttributesResponseResultDimensionUnitName[2:4],
	_AttributesResponseResultDimensionUnitName[4:6],
}

// AttributesResponseResultDimensionUnitNames returns a list of possible string values of AttributesResponseResultDimensionUnit.
func AttributesResponseResultDimensionUnitNames() []string {
	tmp := make([]string, len(_AttributesResponseResultDimensionUnitNames))
	copy(tmp, _AttributesResponseResultDimensionUnitNames)
	return tmp
}

var _AttributesResponseResultDimensionUnitMap = map[AttributesResponseResultDimensionUnit]string{
	AttributesResponseResultDimensionUnitMm: _AttributesResponseResultDimensionUnitName[0:2],
	AttributesResponseResultDimensionUnitCm: _AttributesResponseResultDimensionUnitName[2:4],
	AttributesResponseResultDimensionUnitIn: _AttributesResponseResultDimensionUnitName[4:6],
}

// String implements the Stringer interface.
func (x AttributesResponseResultDimensionUnit) String() string {
	if str, ok := _AttributesResponseResultDimensionUnitMap[x]; ok {
		return str
	}
	return fmt.Sprintf("AttributesResponseResultDimensionUnit(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x AttributesResponseResultDimensionUnit) IsValid() bool {
	_, ok := _AttributesResponseResultDimensionUnitMap[x]
	return ok
}

var _AttributesResponseResultDimensionUnitValue = map[string]AttributesResponseResultDimensionUnit{
	_AttributesResponseResultDimensionUnitName[0:2]: AttributesResponseResultDimensionUnitMm,
	_AttributesResponseResultDimensionUnitName[2:4]: AttributesResponseResultDimensionUnitCm,
	_AttributesResponseResultDimensionUnitName[4:6]: AttributesResponseResultDimensionUnitIn,
}

// ParseAttributesResponseResultDimensionUnit attempts to convert a string to a AttributesResponseResultDimensionUnit.
func ParseAttributesResponseResultDimensionUnit(name string) (AttributesResponseResultDimensionUnit, error) {
	if x, ok := _AttributesResponseResultDimensionUnitValue[name]; ok {
		return x, nil
	}
	return AttributesResponseResultDimensionUnit(0), fmt.Errorf("%s is %w", name, ErrInvalidAttributesResponseResultDimensionUnit)
}

// MarshalText implements the text marshaller method.
func (x AttributesResponseResultDimensionUnit) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *AttributesResponseResultDimensionUnit) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseAttributesResponseResultDimensionUnit(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}
